spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    generate-ddl: false
    open-in-view: true
  datasource:
    url: "jdbc:postgresql://mypostgres:5432/db"
    username: root
    password: toortoor
    driver-class-name: org.postgresql.Driver
